### ISSUE TITLE
SteamVR close

### ISSUE THREAD

**Issue by vrterritory** [BenWoodford/SteamVR-Webkit#14]
Hi There,

Great job!

What is the best way to handle SteamVR close and reconnect when SteamVR is back on track?

**Comment by BenWoodford** [comment]
Close the application and re-open it with SteamVR.

**Comment by vrterritory** [comment]
:D That is a nice way to tell that the question suck :)

I just managed to achieve the scenario I was looking for. Thank you for your time and all the work!
