### ISSUE TITLE
Cookies are not saved between sessions.

### ISSUE THREAD

**Issue by SteffanDonal** [BenWoodford/SteamVR-Webkit#2]
I tried to naively get this working by specifying `CefSettings` with a `CachePath` set, but this doesn't work.  

Any help?

**Comment by BenWoodford** [comment]
Try this
```
SteamVR_WebKit.SteamVR_WebKit.Init(new CefSharp.CefSettings() { PersistSessionCookies = true, CachePath = "cache" });
```

**Comment by SteffanDonal** [comment]
That's what I tried, but I couldn't get it saving.
Wasn't sure if it was because the only way to quit was to CTRL+C or kill the project in Visual Studio, so I tried adding a clean exit calling `Cef.Shutdown();`, but this didn't work either.  

I did have write permissions to the folder, as a ~128KiB file for visited sites was created.

**Comment by BenWoodford** [comment]
Huh, that should work, everywhere else says it does. Very odd.

Shall have to do some reading.

**Comment by amaitland** [comment]
Your `RequestContextSettings` likely has an empty `CachePath`.

http://cefsharp.github.io/api/55.0.0/html/P_CefSharp_RequestContextSettings_CachePath.htm

**Comment by BenWoodford** [comment]
Ah, so they both need the cachepath set then?

**Comment by SteffanDonal** [comment]
Excellent, that fixed the issue.
Turns out it was already exposed as `WebKitOverlay.CachePath`, which must be set before running `.StartBrowser();`
