### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by robnewton** [BenWoodford/SteamVR-Webkit#4]
I saw your code comments about the notifications not working yet and thought I'd share another project I came across through nuget that has a working implementation you might be able to reference.

https://github.com/artumino/SteamVR_HUDCenter

**Comment by BenWoodford** [comment]
Ooo, that's helpful thanks. Unfortunately they don't seem to have provided a sample of actually using the bitmap, but knowing that a blank one can be used is mighty helpful in itself.

Might be able to get these damn things working at some point, I just wish I knew what _all_ the options meant.

**Comment by robnewton** [comment]
Ya thats true. Well for hte time being, I just threw the basic (non-bitmap) notification into a util class so I can throw a message at the screen when I need to.

I haven't looked into your implementation yet but in a simple js callback, I can just call my send notification util method and get something on screen with the message coming in from the JS call.

**Comment by robnewton** [comment]
Added pull #6 to implement this default empty bitmap in JsInterop.Notification.js
