### ISSUE TITLE
Overlays Don't Always Appear

### ISSUE THREAD

**Issue by robnewton** [BenWoodford/SteamVR-Webkit#7]
If the controllers are not on before I run my app then they will never appear. Also if the overlay is attached to a specific controller (left for instance) then if the controllers switch, steamvr handles it and knows that the right became the left, but the overlay does not move over to the new left handed controller.

**Comment by BenWoodford** [comment]
It's a bit of a can of worms this one, as I need to start handling various events like hand swaps, device connections, etc. This is gonna be fun.

**Comment by robnewton** [comment]
Ya I figured. I'll help get it going.

**Comment by robnewton** [comment]
Fixed in [pull request 8](https://github.com/BenWoodford/SteamVR-Webkit/pull/8)
