### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Martin-Oehler** [BenWoodford/SteamVR-Webkit#9]
Hey,
the SteamVR-WebKit-Test runs for me just fine. However after creating a new project, I get a `System.InvalidOperationException` in the `ChromiumWebBrowser` constructor
```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Cef::Initialize() failed
  Source=CefSharp.OffScreen
  StackTrace:
       at CefSharp.OffScreen.ChromiumWebBrowser..ctor(String address, BrowserSettings browserSettings, RequestContext requestContext, Boolean automaticallyCreateBrowser)
       at SteamVR_WebKit.WebKitOverlay.<AsyncBrowser>d__80.MoveNext() in SteamVR-Webkit\SteamVR-WebKit\WebKitOverlay.cs:line 201.
  InnerException: 
```
I copied the program code of the webkit-test, but still no success. Anyone got an idea why I get this exception?

Kind regards,
Martin Oehler

**Comment by BenWoodford** [comment]
Your guess is as good as mine, if you copied the code over exactly there's no reason this should happen...

I've got a project coming up that uses this library so I'll see if I spot anything then.

**Comment by Martin-Oehler** [comment]
Thanks for your answer, I fixed it by recreating project and solution. Looks like something strange broke.
